#!/usr/bin/env bash
# Author
author="Philip Mello <@Microsoft>"
# Version
version="1.1"
# License
license="MIT"
# Date
current_date=$(date +'%b %d, %Y')
# GitHub
github='https://github.com/PhilipMello/aaPanel/'
github2='https://github.com/AtomyCloud/aaPanel/'

script="aPanel Script Automation"
description="Automation for install aaPanel on Ubuntu"

echo "

     ___________           .__     $version
_____\__    ___/___   ____ |  |    $current_date
\__  \ |    | /  _ \ /  _ \|  |    $author
 / __ \|    |(  <_> |  <_> )  |__  $license
(____  /____| \____/ \____/|____/
     \/                          
$github
# --------------------------------------------------------------
# Script     : $script
# Description: $description
# --------------------------------------------------------------
# How to use: Execute atool
# Exemples:
# Manual: atool -h OR atool --h OR atool --help
# --------------------------------------------------------------
"
WHITE=""
BLUE="\033[97;104m"
YELLOW="\033[97;103m"
CYAN="\033[97;106m"
MAGENTA="\033[97;45m"
GREEN="\033[97;102m"
RED="\033[97;41m"
ENDCOLOR="\e[0m"

function zs_install_pkgs() {
    echo -e "
    +-----------------------------------------------------------+
    |${MAGENTA}Installing Pakcages${ENDCOLOR}
    +-----------------------------------------------------------+
    "
    sudo apt-get install \
    wget curl nano htop atop \
    zip unzip p7zip iperf3 stow nmap \
    tcpdump netcat-openbsd mtr sed jq \
    libsctp1 lnav sipcalc ipcalc inetutils-* net-tools -y
}

function zs_install_aapanel_6() {
    echo -e "
    ==================================================================
    |${MAGENTA}aaPanel installation script${ENDCOLOR}
    ==================================================================
    "
    echo Type your hostname URL:
    read hostnameurl
    hostnamectl set-hostname $hostnameurl
    echo "Your Hostname URL is:" $hostnameurl
    echo -e "
    ==================================================================
    |${MAGENTA}Installling aaPanel 6.0.0...${ENDCOLOR}
    ==================================================================
    "
    apt update -y && apt upgrade -y
    apt update -y && apt install wget curl grep nano htop p7zip -y && curl https://rclone.org/install.sh | sudo bash -y
    URL=https://www.aapanel.com/script/install_6.0_en.sh && if [ -f /usr/bin/curl ];then curl -ksSO "$URL" ;else wget --no-check-certificate -O install_6.0_en.sh "$URL";fi;bash install_6.0_en.sh aapanel
}

function zs_install_aapanel_7() {
    echo -e "
    ==================================================================
    |${MAGENTA}aaPanel installation script${ENDCOLOR}
    ==================================================================
    "
    echo Type your hostname URL:
    read hostnameurl
    hostnamectl set-hostname $hostnameurl
    echo "Your Hostname URL is:" $hostnameurl
    echo -e "
    ==================================================================
    |${MAGENTA}Installling aaPanel 7...${ENDCOLOR}
    ==================================================================
    "
    URL=https://www.aapanel.com/script/install_7.0_en.sh && if [ -f /usr/bin/curl ];then curl -ksSO "$URL" ;else wget --no-check-certificate -O install_7.0_en.sh "$URL";fi;bash install_7.0_en.sh aapanel
}


echo "1. Install updates only"
echo "2. Install updates && upgrades"
echo "3. Install tool packages (wget, curl, grep, htop, nano...)"
echo "4. rClone"
echo "5. Install aaPanel 6.0"
echo "6. Install aaPanel 7.0"
read option

case $option in
    1)
        apt update -y
        ;;
    2)
        apt update -y && apt upgrade -y
        ;;
    3)
        zs_install_pkgs
        ;;
    4)
        curl https://rclone.org/install.sh | sudo bash -y
        ;;
    5)
        zs_install_aapanel_6
        ;;
    6)
        zs_install_aapanel_7
        ;;
    *)
        echo "Invalid option"
        ;;
esac

# ---

# Manual
manual() {
    echo -e ""
    echo -e ""

exit 0
}

if [[ $1 == "-h" || $1 == "--help" || "$1" == "--h" ]]; then
    manual
    exit 1
fi
